highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "https://takae-underscore.github.io"  # Sitemap base URL.
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jektex
jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  katex_options:
    trust: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]